var k = exports;

k.POSITION_MODE_MANUAL  = 'manual';
k.POSITION_MODE_AUTO    = 'auto';

k.SPLIT_PANE_HORIZONTAL = 'h';
k.SPLIT_PANE_VERTICAL   = 'v';

k.TOOLBAR_ALIGN_LEFT    = 1;
k.TOOLBAR_ALIGN_RIGHT   = 2;